# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0
version = 1

[[annotations]]
path = [
 "NOTICE",
 "mix.lock",
 "**/VERSION",
 "**/nerves_defconfig",
 "**/darwin_defconfig",
 "**/linux_defconfig",
 "resources/menu-search-tip.gif",
 "test/fixtures/resolver/artifact.tar.gz",
 "test/fixtures/resolver/artifact.tar.xz",
 "test/fixtures/resolver/artifact.tar.zst",
 "test/fixtures/resolver/corrupt.tar.gz",
 "test/fixtures/resolver/corrupt.tar.xz",
 "test/fixtures/resolver/corrupt.tar.zst"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "resources/logo-color.png",
 "resources/logo.png"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Nerves Project Authors"
SPDX-License-Identifier = "LicenseRef-Nerves-Logo"
