# SPDX-FileCopyrightText: 2025 Frank Hunleth
#
# SPDX-License-Identifier: Apache-2.0
#
defmodule Nerves.Tar.ReaderTest do
  use ExUnit.Case, async: true

  alias Nerves.Tar.Entry
  alias Nerves.Tar.Reader

  # Generated by test/support/scripts/create_all_types_fixture.py
  @fixture_tar Path.expand("../../fixtures/all_types.tar", __DIR__)

  # Reused across assertions to keep them readable
  @long_name_file "./long_name_dir/" <> String.duplicate("a", 90) <> ".txt"
  @long_link_target "../" <> String.duplicate("b", 96) <> "/target"
  @both_long_name "./long_name_dir/" <> String.duplicate("c", 90) <> "_sym"
  @both_long_target "../" <> String.duplicate("d", 96) <> "/target"
  @pax_long_target "../../../usr/share/ca-certificates/mozilla/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.crt"

  describe "read_tar/1 with all_types fixture" do
    setup do
      entries = Reader.read_tar(@fixture_tar)
      by_path = Map.new(entries, &{&1.path, &1})
      {:ok, entries: entries, by_path: by_path}
    end

    # -- typeflag '5' ---------------------------------------------------------

    test "reads directories", %{by_path: by_path} do
      # Python's GNU tar does not add a ./ prefix; paths are stored verbatim
      for path <- ["short_dir/", "dev/", "long_name_dir/"] do
        assert %Entry{type: :directory, mode: 0o755} = Map.fetch!(by_path, path)
      end
    end

    # -- typeflag '0' ---------------------------------------------------------

    test "reads a regular file", %{by_path: by_path} do
      entry = Map.fetch!(by_path, "short_dir/regular.txt")
      assert entry.type == :regular
      assert entry.mode == 0o644
      assert entry.size == 24
      assert {:ok, "hello from regular file\n"} == Entry.read_contents(entry)
    end

    # -- typeflag '2' ---------------------------------------------------------

    test "reads a symlink", %{by_path: by_path} do
      entry = Map.fetch!(by_path, "short_dir/link")
      assert entry.type == :symlink
      assert entry.link == "short_target"
    end

    # -- typeflag '1' ---------------------------------------------------------

    test "reads a hard link", %{by_path: by_path} do
      entry = Map.fetch!(by_path, "short_dir/hardlink")
      assert entry.type == :hard_link
      assert entry.link == "short_dir/regular.txt"
    end

    # -- typeflag '3' ---------------------------------------------------------

    test "reads a character device", %{by_path: by_path} do
      entry = Map.fetch!(by_path, "dev/ttyS0")
      assert entry.type == :character_device
      assert entry.mode == 0o660
      assert entry.major_device == 4
      assert entry.minor_device == 64
    end

    # -- typeflag '4' ---------------------------------------------------------

    test "reads a block device", %{by_path: by_path} do
      entry = Map.fetch!(by_path, "dev/sda")
      assert entry.type == :block_device
      assert entry.mode == 0o660
      assert entry.major_device == 8
      assert entry.minor_device == 0
    end

    # -- typeflag 'L' + '0' ---------------------------------------------------

    # Long-name entries are resolved through Entry.put_path which normalizes
    # the path, so they DO get the ./ prefix even though short names do not.
    test "resolves GNU long name (L) for a regular file", %{by_path: by_path} do
      entry = Map.fetch!(by_path, @long_name_file)
      assert entry.type == :regular
      assert entry.mode == 0o644
      assert entry.size == 20
      assert {:ok, "file with long name\n"} == Entry.read_contents(entry)
    end

    # -- typeflag 'K' + '2' ---------------------------------------------------

    # K-only entry: path is short (no L), so no normalization → no ./ prefix.
    # K provides the link target, not the path.
    test "resolves GNU long link (K) for a symlink", %{by_path: by_path} do
      entry = Map.fetch!(by_path, "short_dir/long_link_sym")
      assert entry.type == :symlink
      assert entry.link == @long_link_target
    end

    # -- typeflags 'K' + 'L' + '2' --------------------------------------------

    test "resolves both GNU long name (L) and long link (K) for a symlink", %{by_path: by_path} do
      entry = Map.fetch!(by_path, @both_long_name)
      assert entry.type == :symlink
      assert entry.link == @both_long_target
    end

    # -- internal housekeeping ------------------------------------------------

    test "filters out the root ./ entry", %{entries: entries} do
      refute Enum.any?(entries, &(&1.path == "./"))
    end

    test "does not expose GNU extension entries in the result", %{entries: entries} do
      refute Enum.any?(entries, &(&1.type in [:long_name, :long_link]))
    end
  end

  test "resolves a PAX long link" do
    tar_path = Path.join(System.tmp_dir!(), "nerves_tar_pax_long_link_test.tar")
    on_exit(fn -> File.rm(tar_path) end)

    pax_data = pax_record("linkpath", @pax_long_target)

    File.open!(tar_path, [:write], fn file ->
      write_header(file, "./PaxHeaders/link", ?x, byte_size(pax_data))
      write_data(file, pax_data)

      write_header(
        file,
        "./etc/ssl/certs/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem",
        ?2,
        0,
        String.slice(@pax_long_target, 0, 100)
      )

      IO.binwrite(file, :binary.copy(<<0>>, 1024))
    end)

    entry =
      tar_path
      |> Reader.read_tar()
      |> Enum.find(
        &(&1.path ==
            "./etc/ssl/certs/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem")
      )

    assert entry.link == @pax_long_target
  end

  defp pax_record(key, value) do
    record = " #{key}=#{value}\n"

    1..10
    |> Enum.find_value(fn length_digits ->
      length = byte_size(record) + length_digits
      pax_record = "#{length}#{record}"
      if byte_size(pax_record) == length, do: pax_record
    end)
  end

  defp write_header(file, path, typeflag, size, link \\ "") do
    header1 =
      [
        string_field(path, 100),
        octal_field(0o644, 8),
        octal_field(0, 8),
        octal_field(0, 8),
        octal_field(size, 12),
        octal_field(0, 12)
      ]
      |> IO.iodata_to_binary()

    header2 =
      [
        typeflag,
        string_field(link, 100),
        "ustar\0",
        "00",
        :binary.copy(<<0>>, 32),
        :binary.copy(<<0>>, 32),
        octal_field(0, 8),
        octal_field(0, 8),
        :binary.copy(<<0>>, 155)
      ]
      |> IO.iodata_to_binary()

    checksum = ?\s * 8 + Enum.sum(for <<byte <- header1 <> header2>>, do: byte)
    IO.binwrite(file, [header1, octal_field(checksum, 8), header2, :binary.copy(<<0>>, 12)])
  end

  defp write_data(file, data) do
    :ok = IO.binwrite(file, data)
    padding = rem(512 - rem(byte_size(data), 512), 512)
    :ok = IO.binwrite(file, :binary.copy(<<0>>, padding))
  end

  defp string_field(value, length) do
    value <> :binary.copy(<<0>>, length - byte_size(value))
  end

  defp octal_field(value, length) do
    value
    |> Integer.to_string(8)
    |> String.pad_leading(length - 1, "0")
    |> then(&[&1, 0])
  end
end
