#!/bin/sh
# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

set -e

# This script builds nerves_system_br-based Nerves packages.
# nerves_system_br is expected to be included as a required dependency.
setup() {
  /workspace/nerves_system_br/create-build.sh "/workspace/$NERVES_ARTIFACT_APP/nerves_defconfig" /workspace/build
}

clean() {
  rm -rf /workspace/build
  mkdir -p /workspace/build
}

[ "$#" -gt 0 ] || set -- setup build

for command in "$@"; do
  case "$command" in
    clean)
      clean
      ;;

    setup)
      setup
      ;;

    build)
      mkdir -p "$NERVES_ARTIFACT_DIR"
      cd /workspace/build
      make
      make system NERVES_ARTIFACT_NAME="${NERVES_ARTIFACT_APP}-portable-${NERVES_ARTIFACT_VERSION}-${NERVES_ARTIFACT_SOURCE_FINGERPRINT}"
      cp ./*.tar.* "$NERVES_ARTIFACT_DIR/"
      ;;

    shell)
      cd /workspace/build
      exec /bin/bash
      ;;

    *)
      echo "Unknown command: $command" >&2
      echo "Expected one of: clean setup build shell" >&2
      exit 1
      ;;
  esac
done
